CREATE DATABASE FlaxNam;

USE FlaxNam;

CREATE TABLE Login(
loginID INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
contra VARCHAR(20) NOT NULL
);

CREATE TABLE Usuario(
usuarioID INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(20) NOT NULL,
apellido VARCHAR(20) NOT NULL,
correo  VARCHAR(40) NOT NULL,
telefono VARCHAR(8) NOT NULL,
edad INT NOT NULL,
usernameID INT,
FOREIGN KEY  (usernameID) REFERENCES Login(loginID)
);

CREATE TABLE Juegos(
juegosID INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(35) NOT NULL,
clasificacion VARCHAR(4) NOT NULL,
genero VARCHAR(20) NOT NULL,
precio INT NOT NULL,
sinopsis TEXT NOT NULL
);

CREATE TABLE Articulos(
articuloID INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(30) NOT NULL,
cuerpo LONGTEXT,
juegosID INT,
usernameID INT,
FOREIGN KEY (juegosID) REFERENCES Juegos(juegosID),
FOREIGN KEY (usernameID) REFERENCES Login(loginID)
);